#!/bin/bash

echo "=================================================================================="
echo "TEST DES ENDPOINTS DE PRODUITS - VÉRIFICATION DES IMAGES CLOUDINARY"
echo "=================================================================================="
echo ""

echo "1. OBTENIR UN TOKEN D'AUTHENTIFICATION:"
echo "----------------------------------------"
echo "curl -X POST http://localhost:3333/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"uid\":\"votre_email@example.com\",\"password\":\"votre_password\"}'"
echo ""
echo "Copiez le token de la réponse (champ: token.token)"
echo ""

echo "2. TEST GET /products/all (tous les produits)"
echo "----------------------------------------"
echo "curl -X GET http://localhost:3333/products/all \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -H 'Content-Type: application/json' | jq '.'"
echo ""
echo "Vérifiez que chaque produit a:"
echo "  - image: URL Cloudinary (ou null)"
echo "  - images: Tableau d'URLs Cloudinary"
echo ""

echo "3. TEST GET /products/get-products/:id (produit spécifique)"
echo "----------------------------------------"
echo "curl -X GET http://localhost:3333/products/get-products/1 \\"
echo "  -H 'Content-Type: application/json' | jq '.'"
echo ""
echo "Vérifiez que le produit a:"
echo "  - image: URL Cloudinary (ou null)"
echo "  - images: Tableau d'URLs Cloudinary"
echo ""

echo "4. TEST GET /products/boutique/:userId (produits d'un vendeur)"
echo "----------------------------------------"
echo "curl -X GET http://localhost:3333/products/boutique/USER_ID \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -H 'Content-Type: application/json' | jq '.'"
echo ""
echo "Vérifiez que chaque produit a:"
echo "  - image: URL Cloudinary (ou null)"
echo "  - images: Tableau d'URLs Cloudinary"
echo ""

echo "5. TEST GET /products/category/:categoryId (produits par catégorie)"
echo "----------------------------------------"
echo "curl -X GET http://localhost:3333/products/category/CATEGORY_ID \\"
echo "  -H 'Content-Type: application/json' | jq '.'"
echo ""
echo "Vérifiez que chaque produit a:"
echo "  - image: URL Cloudinary (ou null)"
echo "  - images: Tableau d'URLs Cloudinary"
echo ""

echo "=================================================================================="
echo "STRUCTURE ATTENDUE DE LA RÉPONSE:"
echo "=================================================================================="
echo ""
echo "{"
echo "  \"products\": ["
echo "    {"
echo "      \"id\": 1,"
echo "      \"name\": \"Produit exemple\","
echo "      \"description\": \"Description\","
echo "      \"price\": 15000,"
echo "      \"stock\": 50,"
echo "      \"category\": { ... },"
echo "      \"image\": \"https://res.cloudinary.com/.../products/image1.jpg\","
echo "      \"images\": ["
echo "        \"https://res.cloudinary.com/.../products/image2.jpg\","
echo "        \"https://res.cloudinary.com/.../products/image3.jpg\""
echo "      ],"
echo "      \"vendeur\": { ... }"
echo "    }"
echo "  ]"
echo "}"
echo ""

echo "=================================================================================="
echo "EXEMPLE COMPLET DE TEST:"
echo "=================================================================================="
echo ""
echo "# 1. Obtenir un token"
echo "TOKEN=\$(curl -s -X POST http://localhost:3333/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"uid\":\"votre_email\",\"password\":\"votre_password\"}' | jq -r '.token.token')"
echo ""
echo "# 2. Tester getAllProducts"
echo "curl -s -X GET http://localhost:3333/products/all \\"
echo "  -H \"Authorization: Bearer \$TOKEN\" \\"
echo "  -H 'Content-Type: application/json' | jq '.products[0] | {id, name, image, images}'"
echo ""
echo "# 3. Tester getProductById (remplacez 1 par un ID réel)"
echo "curl -s -X GET http://localhost:3333/products/get-products/1 \\"
echo "  -H 'Content-Type: application/json' | jq '.product | {id, name, image, images}'"
echo ""

echo "=================================================================================="
echo "VÉRIFICATIONS À FAIRE:"
echo "=================================================================================="
echo ""
echo "✅ Les URLs d'images doivent commencer par 'https://res.cloudinary.com/'"
echo "✅ Le champ 'image' doit contenir l'URL de l'image principale (ou null)"
echo "✅ Le champ 'images' doit être un tableau d'URLs Cloudinary"
echo "✅ Les images doivent correspondre aux images enregistrées pour chaque produit"
echo ""

