#!/bin/bash

echo "=================================================================================="
echo "TEST DE CRÉATION D'UN PRODUIT"
echo "=================================================================================="
echo ""

# 1. Instructions pour obtenir un token
echo "1. OBTENIR UN TOKEN D'AUTHENTIFICATION:"
echo "----------------------------------------"
echo "curl -X POST http://localhost:3333/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"uid\":\"votre_email@example.com\",\"password\":\"votre_password\"}'"
echo ""
echo "Copiez le token de la réponse (champ: token.token)"
echo ""

# 2. Structure de la commande pour créer un produit
echo "2. CRÉER UN PRODUIT (remplacez YOUR_TOKEN par votre token):"
echo "----------------------------------------"
echo ""
echo "curl -X POST http://localhost:3333/products/store \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -F 'name=Produit Test' \\"
echo "  -F 'description=Description du produit de test' \\"
echo "  -F 'price=15000' \\"
echo "  -F 'stock=20' \\"
echo "  -F 'category=Test Category' \\"
echo "  -F 'image=@/chemin/vers/image1.jpg' \\"
echo "  -F 'image1=@/chemin/vers/image2.jpg' \\"
echo "  -F 'image2=@/chemin/vers/image3.jpg' \\"
echo "  -F 'image3=@/chemin/vers/image4.jpg' \\"
echo "  -F 'image4=@/chemin/vers/image5.jpg'"
echo ""

# 3. Exemple avec des données minimales (sans images)
echo "3. CRÉER UN PRODUIT SANS IMAGES (pour test rapide):"
echo "----------------------------------------"
echo ""
echo "curl -X POST http://localhost:3333/products/store \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -F 'name=Produit Test Sans Images' \\"
echo "  -F 'description=Description du produit' \\"
echo "  -F 'price=15000' \\"
echo "  -F 'stock=20' \\"
echo "  -F 'category=Test Category'"
echo ""

# 4. Vérifier les produits créés
echo "4. VÉRIFIER LES PRODUITS CRÉÉS:"
echo "----------------------------------------"
echo ""
echo "curl -X GET http://localhost:3333/products/all \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -H 'Content-Type: application/json'"
echo ""

echo "=================================================================================="
echo "STRUCTURE DE LA RÉPONSE ATTENDUE:"
echo "=================================================================================="
echo ""
echo "{"
echo "  \"message\": \"Produit créé avec succès\","
echo "  \"product\": {"
echo "    \"id\": 1,"
echo "    \"name\": \"Produit Test\","
echo "    \"description\": \"Description du produit\","
echo "    \"price\": 15000,"
echo "    \"stock\": 20,"
echo "    \"category\": { ... },"
echo "    \"media\": { ... }"
echo "  },"
echo "  \"medias\": ["
echo "    {"
echo "      \"id\": 1,"
echo "      \"mediaUrl\": \"https://res.cloudinary.com/...\","
echo "      \"mediaType\": \"jpg\""
echo "    }"
echo "  ]"
echo "}"
echo ""

echo "=================================================================================="
echo "ENDPOINT: POST /products/store"
echo "AUTHENTIFICATION: REQUISE (Bearer Token)"
echo "RÔLE: Vendeur uniquement"
echo "=================================================================================="

