#!/bin/bash

echo "=================================================================================="
echo "INSTRUCTIONS POUR TESTER LA CRÉATION D'UN PRODUIT AVEC URL UNSPLASH"
echo "=================================================================================="
echo ""

echo "1. OBTENIR UN TOKEN:"
echo "----------------------------------------"
echo "curl -X POST http://localhost:3333/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"uid\":\"votre_email@example.com\",\"password\":\"votre_password\"}'"
echo ""
echo "Copiez le token de la réponse (champ: token.token)"
echo ""

echo "2. CRÉER UN PRODUIT AVEC URL UNSPLASH:"
echo "----------------------------------------"
echo "curl -X POST http://localhost:3333/products/store \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -F 'name=Produit Test Unsplash' \\"
echo "  -F 'description=Produit avec image Unsplash' \\"
echo "  -F 'price=25000' \\"
echo "  -F 'stock=15' \\"
echo "  -F 'category=Test Category' \\"
echo "  -F 'image=https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop' \\"
echo "  -F 'image1=https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop'"
echo ""

echo "3. VÉRIFIER LE PRODUIT CRÉÉ (remplacez PRODUCT_ID par l'ID retourné):"
echo "----------------------------------------"
echo "curl -X GET http://localhost:3333/products/get-products/PRODUCT_ID \\"
echo "  -H 'Content-Type: application/json'"
echo ""

echo "4. VÉRIFIER TOUS LES PRODUITS:"
echo "----------------------------------------"
echo "curl -X GET http://localhost:3333/products/all \\"
echo "  -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "  -H 'Content-Type: application/json'"
echo ""

echo "=================================================================================="
echo "STRUCTURE DE LA RÉPONSE ATTENDUE:"
echo "=================================================================================="
echo ""
echo "Le produit doit avoir:"
echo "  - image: URL Cloudinary (ex: https://res.cloudinary.com/.../products/...) "
echo "  - images: Tableau d'URLs Cloudinary"
echo ""
echo "Exemple:"
echo "{"
echo "  \"product\": {"
echo "    \"id\": 1,"
echo "    \"name\": \"Produit Test Unsplash\","
echo "    \"image\": \"https://res.cloudinary.com/dnn2ght5x/image/upload/v.../products/...\","
echo "    \"images\": ["
echo "      \"https://res.cloudinary.com/dnn2ght5x/image/upload/v.../products/...\""
echo "    ]"
echo "  }"
echo "}"
echo ""

echo "=================================================================================="
echo "NOTE IMPORTANTE:"
echo "=================================================================================="
echo "Les URLs Unsplash seront automatiquement téléchargées et uploadées sur Cloudinary."
echo "Les URLs stockées en base seront des URLs Cloudinary, pas des URLs Unsplash."
echo ""

