export enum ProductCategory {
  ELECTRONICS = 'electronics',
  FASHION = 'fashion',
  HOME = 'home',
  BEAUTY = 'beauty',
  SPORTS = 'sports',
  TOYS = 'toys',
  BOOKS = 'books',
  GARDEN = 'garden',
  AUTOMOTIVE = 'automotive',
  HEALTH = 'health',
  PET_SUPPLIES = 'pet_supplies',
  MUSIC = 'music',
  MOVIES = 'movies',
  GAMES = 'games',
  OFFICE = 'office',
  GROCERIES = 'groceries',
  TRAVEL = 'travel',
  KITCHEN = 'kitchen',
  BABY = 'baby',
  STATIONERY = 'stationery',
  FURNITURE = 'furniture',
  ART = 'art',
  HANDMADE = 'handmade',
  SOFTWARE = 'software',
  VIDEO_GAMES = 'video_games',
  FITNESS = 'fitness',
  OUTDOORS = 'outdoors',
  CLOTHING = 'clothing',
  FOOTWEAR = 'footwear',
  ACCESSORIES = 'accessories',
  JEWELRY = 'jewelry',
  WATCHES = 'watches',
  BAGS = 'bags',
  SUNGLASSES = 'sunglasses',
  BELTS = 'belts',
  SCARVES = 'scarves',
  HATS = 'hats',
  SOCKS = 'socks',
  UNDERWEAR = 'underwear',
  SWIMWEAR = 'swimwear',
  ACTIVEWEAR = 'activewear',
  LOUNGEWEAR = 'loungewear',
  ATHLETICWEAR = 'athleticwear',
  CASUALWEAR = 'casualwear',
  FORMALWEAR = 'formalwear',
  OUTERWEAR = 'outerwear',
  COATS = 'coats',
  JACKETS = 'jackets',
  PARKAS = 'parkas',
  VESTS = 'vests',
  RAINCOATS = 'raincoats',
  BOMBERS = 'bombers',
  BLAZERS = 'blazers',
  CARDIGANS = 'cardigans',
}

export const ProductCategoryLabels: Record<ProductCategory, string> = {
  [ProductCategory.ELECTRONICS]: 'électronique',
  [ProductCategory.FASHION]: 'mode',
  [ProductCategory.HOME]: 'maison',
  [ProductCategory.BEAUTY]: 'beauté',
  [ProductCategory.SPORTS]: 'sports',
  [ProductCategory.TOYS]: 'jouets',
  [ProductCategory.BOOKS]: 'livres',
  [ProductCategory.GARDEN]: 'jardin',
  [ProductCategory.AUTOMOTIVE]: 'automobile',
  [ProductCategory.HEALTH]: 'santé',
  [ProductCategory.PET_SUPPLIES]: 'animaux',
  [ProductCategory.MUSIC]: 'musique',
  [ProductCategory.MOVIES]: 'films',
  [ProductCategory.GAMES]: 'jeux',
  [ProductCategory.OFFICE]: 'bureau',
  [ProductCategory.GROCERIES]: 'épicerie',
  [ProductCategory.TRAVEL]: 'voyage',
  [ProductCategory.KITCHEN]: 'cuisine',
  [ProductCategory.BABY]: 'bébé',
  [ProductCategory.STATIONERY]: 'papeterie',
  [ProductCategory.FURNITURE]: 'meubles',
  [ProductCategory.ART]: 'art',
  [ProductCategory.HANDMADE]: 'fait main',
  [ProductCategory.SOFTWARE]: 'logiciels',
  [ProductCategory.VIDEO_GAMES]: 'jeux vidéo',
  [ProductCategory.FITNESS]: 'fitness',
  [ProductCategory.OUTDOORS]: 'extérieur',
  [ProductCategory.CLOTHING]: 'vêtements',
  [ProductCategory.FOOTWEAR]: 'chaussures',
  [ProductCategory.ACCESSORIES]: 'accessoires',
  [ProductCategory.JEWELRY]: 'bijoux',
  [ProductCategory.WATCHES]: 'montres',
  [ProductCategory.BAGS]: 'sacs',
  [ProductCategory.SUNGLASSES]: 'lunettes de soleil',
  [ProductCategory.BELTS]: 'ceintures',
  [ProductCategory.SCARVES]: 'écharpes',
  [ProductCategory.HATS]: 'chapeaux',
  [ProductCategory.SOCKS]: 'chaussettes',
  [ProductCategory.UNDERWEAR]: 'sous-vêtements',
  [ProductCategory.SWIMWEAR]: 'maillots de bain',
  [ProductCategory.ACTIVEWEAR]: 'tenues sport',
  [ProductCategory.LOUNGEWEAR]: 'tenues intérieur',
  [ProductCategory.ATHLETICWEAR]: 'vêtements athlétiques',
  [ProductCategory.CASUALWEAR]: 'tenues décontractées',
  [ProductCategory.FORMALWEAR]: 'tenues habillées',
  [ProductCategory.OUTERWEAR]: 'manteaux',
  [ProductCategory.COATS]: 'manteaux longs',
  [ProductCategory.JACKETS]: 'vestes',
  [ProductCategory.PARKAS]: 'parkas',
  [ProductCategory.VESTS]: 'gilets',
  [ProductCategory.RAINCOATS]: 'imperméables',
  [ProductCategory.BOMBERS]: 'bombers',
  [ProductCategory.BLAZERS]: 'blazers',
  [ProductCategory.CARDIGANS]: 'cardigans',
}

// 🔁 Mapping inverse : français -> anglais
export const LabelToProductCategory: Record<string, ProductCategory> = Object.fromEntries(
  Object.entries(ProductCategoryLabels).map(([key, label]) => [
    label.toLowerCase(),
    key as ProductCategory,
  ])
)
